services:
  - type: web
    name: react-movie-app
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_TMDB_BEARER_TOKEN
        sync: false
